# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Continuous Delivery

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js rebuild --verbose
      - run: |
          git config --local user.email "david@daviwil.com"
          git config --local user.name "David Wilson"
          node common/scripts/install-run-rush.js publish --apply --publish --target-branch master --commit --set-access-level public
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
